Repository aws-samples/aws-serverless-airline-booking, pull requests merged in 2020-07, with the labels that each got.

#117 chore: updated stale dependencies, deprecated packages
  src/backend/loyalty/.eslintignore
  src/backend/loyalty/.eslintrc
  src/backend/loyalty/package-lock.json
  src/backend/loyalty/package.json
Labels: front-end

#112 Remove log-processing stack in favour of EMF
  Makefile
  bin/local_env_script.sh
  docs/decision_log.md
  src/backend/booking/README.md
  src/backend/booking/src/cancel-booking/cancel.py
  src/backend/booking/src/cancel-booking/requirements.txt
  src/backend/booking/src/confirm-booking/confirm.py
  src/backend/booking/src/confirm-booking/requirements.txt
  src/backend/booking/src/notify-booking/notify.py
  src/backend/booking/src/notify-booking/requirements.txt
  src/backend/booking/src/reserve-booking/requirements.txt
  src/backend/booking/src/reserve-booking/reserve.py
  src/backend/booking/template.yaml
  src/backend/loyalty/template.yaml
  src/backend/payment/README.md
  src/backend/payment/src/collect-payment/collect.py
  src/backend/payment/src/collect-payment/requirements.txt
  src/backend/payment/src/refund-payment/refund.py
  src/backend/payment/src/refund-payment/requirements.txt
  src/backend/payment/template.yaml
Labels: enhancement

#123 fix: lodash CVE-2020-8203
  src/e2e-tests/package-lock.json
  src/e2e-tests/package.json
Labels: dependencies

#124 fix/CVE-2020-13822
  src/backend/loyalty/package-lock.json
Labels: dependencies

#126 fix: CVE-2020-13822 frontend, ts-jest, and vue-cli
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: dependencies
